### ISSUE TITLE
missing file/path: in `require': cannot load such file -- ./lib/wpstools/wpstools_helper (LoadError)

### ISSUE THREAD

**Issue by tspedw** [delvelabs/vane#3]
grep -i wpstools_helper vanetools.rb
require File.dirname(**FILE**) + '/lib/wpstools/wpstools_helper'

in `require': cannot load such file -- ./lib/wpstools/wpstools_helper (LoadError)

**Comment by gabtremblay** [comment]
Problem due to project renaming. Fixed.
